export default function AITitleHeader() {
    return (
        <div className="w-full flex flex-col items-center justify-center py-16 px-4 bg-gradient-to-r from-blue-600/90 to-violet-600/90 dark:from-blue-800 dark:to-violet-800 text-white text-center">
            <div className="max-w-4xl mx-auto">
                <h1 className="text-4xl md:text-5xl lg:text-6xl font-bold mb-4 tracking-tight">
                    AI Title Generator
                    <span className="block mt-2 bg-clip-text text-transparent bg-gradient-to-r from-blue-200 to-purple-200">
                        Craft Perfect Headlines Instantly
                    </span>
                </h1>
                
                <p className="text-xl md:text-2xl font-light mb-8 text-blue-100 max-w-2xl mx-auto">
                    Supercharge your content with captivating titles generated by our advanced AI
                </p>
                
                <p className="text-base md:text-lg text-blue-50/90 max-w-3xl mx-auto mb-10">
                    Our state-of-the-art machine learning algorithms analyze millions of high-performing 
                    headlines to create engaging, click-worthy titles tailored to your specific content 
                    and audience. Transform your writing with titles that convert.
                </p>
                
                <div className="flex flex-col sm:flex-row gap-4 justify-center">
                    <button className="px-6 py-3 bg-white text-violet-700 rounded-md font-medium hover:bg-blue-50 transition-colors">
                        Generate Title
                    </button>
                    <button className="px-6 py-3 bg-transparent border border-white text-white rounded-md font-medium hover:bg-white/10 transition-colors">
                        View Examples
                    </button>
                </div>
            </div>
        </div>
    );
}